---
title: "Codebuch_Frauen"
author: "Ben"
date: "2025-09-10"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Codebuch Resistance

**Edgelist**:
from: Name Widerstandskämpferin
to: Name Widerstandskämpferin/Organisation
relation: Art der Zusammenarbeit:
relation: 1 = Mitgliedschaft , 2 = gemeinsame Aktion, 3 = Verwandtschaft, 4 = gemeinsame
Verhaftung, 5 = verheiratet, 6 = gemeinsam in Verhaftung

**Nodelist**:
id: kurzel + geburtsjahr
name: Name Widerstandskämpferin
type: 1 = Person, 2 = Organisation
nationality: auf Englisch, klein, Beispiel: german
death_place: auf Englisch, klein
death_cause: natural, executed, accident, illness
role: Role inn Struktur z.B founder, leader, member
activity: messenger = Nachrichtendienst, refugee = Fluchthilfe, press = Untergrundpresse,
armed = bewaffneter Widerstand, spionage = Spionage, sabotage = Sabotage
arrested: 1 = ja, 2 = nein
kz: 1 = ja, 2 = nein
fled: 1 = ja, 2 = nein
rescued: 1 = ja, 2 = nein

